power <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?",nrows=2075259, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
power1 <- subset(power, Date %in% c("1/2/2007","2/2/2007"))
power1$Date <- as.Date(power1$Date, format="%d/%m/%Y")
powertime <- paste(as.Date(power1$Date), power1$Time)
power1$Datetime <- as.POSIXct(powertime)

par(mfrow=c(2,2), mar=c(4,4,2,1), oma=c(0,0,2,0))
with(power1, plot(Global_active_power~Datetime, type="l", ylab="Global Active Power", xlab=""))
with(power1, plot(Voltage~Datetime, type="l", ylab="Voltage ", xlab="datetime"))
with(power1, plot(Sub_metering_1~Datetime, type="l", ylab="Energy sub metering", xlab=""))
lines(power1$Sub_metering_2~power1$Datetime,col='red')
lines(power1$Sub_metering_3~power1$Datetime,col='blue')
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
with(power1, plot(Global_reactive_power~Datetime, type="l", ylab="Global_reactive_power", xlab="datetime"))

png("plot4.png", width=480, height=480)
dev.off()